apiVersion: apps/v1
kind: Deployment
metadata:
  name: octopub-audit-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: auditservice
  template:
    metadata:
      labels:
        component: auditservice
    spec:
      containers:
        - name: auditservice
          image: index.docker.io/twerthi/octopub-audit-microservice-mysql:2025.11.09.50
          ports:
            - name: http-audit
              containerPort: 10000
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: database-password
            - name: DATABASE_HOSTNAME
              value: "192.168.1.64"
            - name: DATABASE_PORT
              value: "30000"
            - name: DATABASE_NAME
              value: "octopub_clusterpi_Development"
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: database-user
            - name: MIGRATE_AT_START
              value: "false"
            - name: COGNITO_DISABLE_AUTH
              value: "true"