apiVersion: v1
kind: Service
metadata:
  name: octopub-audit-cluster-ip
spec:
  type: ClusterIP
  selector:
    component: auditservice
  ports:
    - port: 10000
      targetPort: 10000
      name: http-audit