# ex-secrets.yaml 
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-database-credentials
spec:
  refreshInterval: "15s" #This specifies the time interval at which the ExternalSecret controller will refresh the secrets.
  secretStoreRef: # This object contains the reference to the Vault secret store to be used.
    name: vault-backend
    kind: ClusterSecretStore
  target: #This specifies the target Kubernetes secret that the \
  #ExternalSecret will create.
    name: database-credentials #The name of the Kubernetes secret that 
    #will be created.
    creationPolicy: Owner # In this case, the ExternalSecret will \
    #act as the owner of the target Kubernetes Secret.
  data: # This is an array of secret key-value pairs that the \
  #ExternalSecret will retrieve from the Vault secret store and store \
  #in the Kubernetes secret.
    - secretKey: database-user #This specifies the key name for the \
    #secret value in the Kubernetes secret.
      remoteRef: #This is an object that contains the reference to the \
      #secret in the Vault secret store.
        key: "mysqlserver" # This specifies the path to the secret \
        #in the Vault secret store
        property: SA_USERNAME #This specifies the name of the \
        #secret property to retrieve from the Vault secret.
    - secretKey: database-password
      remoteRef:
        key: "mysqlserver"
        property: SA_PASSWORD