apiVersion: apps/v1
kind: Deployment
metadata:
  name: octopub-productservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: productservice
  template:
    metadata:
      labels:
        component: productservice
    spec:
      containers:
        - name: productservice
          image: #{Octopus.Action.Package[octopub-products-microservice-mysql].Registry}/#{Octopus.Action.Package[octopub-products-microservice-mysql].PackageId}:#{Octopus.Action.Package[octopub-products-microservice-mysql].PackageVersion}
          ports:
            - name: http-product
              containerPort: 8083
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: database-password
            - name: DATABASE_HOSTNAME
              value: "#{MySQL.Server.Name}"
            - name: DATABASE_PORT
              value: "#{MySQL.Server.Port}"
            - name: DATABASE_NAME
              value: "octopub_clusterpi_#{Octopus.Environment.Name}"
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: database-user
            - name: MIGRATE_AT_START
              value: "#{Project.EnvironmentVariable.MigrateAtStart}"
            - name: COGNITO_DISABLE_AUTH
              value: "#{Project.EnvironmentVariables.CognitoDisableAuth}"