apiVersion: v1
kind: Service
metadata:
  name: octopub-frontend-cluster-ip
spec:
  type: ClusterIP
  selector:
    component: web
  ports:
    - port: 8080
      targetPort: 8080
      name: http-port