apiVersion: v1
kind: Service
metadata:
  name: octopub-productservice-cluster-ip
spec:
  type: ClusterIP
  selector:
    component: productservice
  ports:
    - port: 8083
      targetPort: 8083
      name: http-product