apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octopub-test-products
  annotations:
    codefresh.io/product: octopub
spec:
  project: default
  source:
    repoURL: https://github.com/twerthi/octopub.git
    targetRevision: HEAD
    path: codefresh/helm/octopub-products-mysql/test
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true