apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octopub-production-products
  annotations:
    codefresh.io/product: octopub
spec:
  project: default
  source:
    repoURL: https://github.com/twerthi/octopub.git
    targetRevision: HEAD
    path: codefresh/helm/octopub-products-mysql/production
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    syncOptions:
    - Validate=false
    - CreateNamespace=true