name: Octopus Ephemeral Environments Demo
permissions:
  contents: write
  packages: write
on:
  pull_request:
    branches:
      - main
  # push:
  #   branches:
  #     - main

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - name: Create Ephemeral Environment
        id: create_ephemeral_environment
        uses: OctopusDeploy/create-ephemeral-environment@v1
        with:
          server: ${{ secrets.LOCAL_OCTOPUS_SERVER_URL }}
          api_key: ${{ secrets.LOCAL_OCTOPUS_API_KEY }}
          name: 'ephemeral-environment-pr-${{ github.event.pull_request.number }}'
          project: 'Ephemeral Environments'
          space: 'Default'

      - name: Create a release in Octopus Deploy üêô
        id: create_a_release_in_octopus_deploy  
        uses: OctopusDeploy/create-release-action@v4
        with:
          project: 'Ephemeral Environments'
          server: ${{ secrets.LOCAL_OCTOPUS_SERVER_URL }}
          api_key: ${{ secrets.LOCAL_OCTOPUS_API_KEY }}
          space: 'Default'

      - name: Deploy a release in Octopus Deploy üêô
        id: deploy_a_release_in_octopus_deploy
        uses: OctopusDeploy/deploy-release-action@v4
        env:
          OCTOPUS_API_KEY: ${{ secrets.LOCAL_OCTOPUS_API_KEY }}
          OCTOPUS_URL: ${{ secrets.LOCAL_OCTOPUS_SERVER_URL }}
          OCTOPUS_SPACE: 'Default'
        with:
          project: 'Ephemeral Environments'
          release_number: ${{ steps.create_a_release_in_octopus_deploy.outputs.release_number }}
          environments: |
            'ephemeral-environment-pr-${{ github.event.pull_request.number }}'
